### ISSUE TITLE
Lets switch to caniuse-light

### ISSUE THREAD

**Issue by kof** [cssinjs/caniuse-support#2]
Autoprefixer is using the light version of caniuse, I guess we can switch this one as well.

**Comment by alinhle** [comment]
@kof I think it's better to keep the original caniuse. When I was working on `css-vendor` I had to do a lot of changes to the `caniuse-db` and it took some time to wait for a release. Changing this to `caniuse-light` will increase the time to get the changes into a release (PR -> caniuse -> release -> caniuse-light -> release). As this project is probably only used in `dev` it does not affect production builds.

**Comment by kof** [comment]
The problem is that autoprefixer is using light and we are running tests comparing with autoprefixer, no? So we are loading both databases and might run into inconsistencies.

**Comment by alinhle** [comment]
I guess it makes sense to do the switch, as long as `caniuse-light` didn't strip any data that we need.

**Comment by AleshaOleg** [comment]
Here is a PR: https://github.com/wikiwi/caniuse-support/pull/3

**Comment by AleshaOleg** [comment]
We can close this, I did a migration - https://github.com/cssinjs/caniuse-support/pull/5/files
